/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as DemoRouteImport } from './routes/_demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioAccountIdRouteImport } from './routes/portfolio.$accountId'
import { Route as DemoDemoRouteImport } from './routes/_demo.demo'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/_demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioAccountIdRoute = PortfolioAccountIdRouteImport.update({
  id: '/$accountId',
  path: '/$accountId',
  getParentRoute: () => PortfolioRoute,
} as any)
const DemoDemoRoute = DemoDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => DemoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/settings': typeof SettingsRoute
  '/demo': typeof DemoDemoRoute
  '/portfolio/$accountId': typeof PortfolioAccountIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/settings': typeof SettingsRoute
  '/demo': typeof DemoDemoRoute
  '/portfolio/$accountId': typeof PortfolioAccountIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_demo': typeof DemoRouteWithChildren
  '/approvals': typeof ApprovalsRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/settings': typeof SettingsRoute
  '/_demo/demo': typeof DemoDemoRoute
  '/portfolio/$accountId': typeof PortfolioAccountIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/portfolio'
    | '/settings'
    | '/demo'
    | '/portfolio/$accountId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/portfolio'
    | '/settings'
    | '/demo'
    | '/portfolio/$accountId'
  id:
    | '__root__'
    | '/'
    | '/_demo'
    | '/approvals'
    | '/portfolio'
    | '/settings'
    | '/_demo/demo'
    | '/portfolio/$accountId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRouteWithChildren
  ApprovalsRoute: typeof ApprovalsRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_demo': {
      id: '/_demo'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$accountId': {
      id: '/portfolio/$accountId'
      path: '/$accountId'
      fullPath: '/portfolio/$accountId'
      preLoaderRoute: typeof PortfolioAccountIdRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/_demo/demo': {
      id: '/_demo/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoDemoRouteImport
      parentRoute: typeof DemoRoute
    }
  }
}

interface DemoRouteChildren {
  DemoDemoRoute: typeof DemoDemoRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoDemoRoute: DemoDemoRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface PortfolioRouteChildren {
  PortfolioAccountIdRoute: typeof PortfolioAccountIdRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioAccountIdRoute: PortfolioAccountIdRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRouteWithChildren,
  ApprovalsRoute: ApprovalsRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
